site_name: Deptool
site_url: https://docs.ruuda.nl/deptool
repo_url: https://github.com/ruuda/deptool
strict: true

theme:
  name: null
  custom_dir: docs/theme

markdown_extensions:
  - codehilite
  - footnotes
  - toc:
      permalink: true
      permalink_title: null

nav:
  - "Overview": "index.md"
  - "User guide":
      - "Tutorial": "tutorial.md"
      - "User management": "user_management.md"
      - "Building": "building.md"
  - "Reference":
      - "Directory layout": "directory_layout.md"
      - "Manifests": "manifests.md"
      - "Deployment phases": "deployment_phases.md"
      - "The store": "store.md"
  - "Command reference":
      - "deptool": "cmd/deptool.md"
      - "deptool init": "cmd/deptool_init.md"
      - "deptool deploy": "cmd/deptool_deploy.md"
      - "deptool sync": "cmd/deptool_sync.md"
      - "deptool ping": "cmd/deptool_ping.md"
