site_name: Deptool
site_url: https://docs.ruuda.nl/deptool
repo_url: https://github.com/ruuda/deptool
strict: true

theme:
  name: null
  custom_dir: docs/theme

markdown_extensions:
  - codehilite
  - footnotes
  - toc:
      permalink: true
      permalink_title: null

nav:
  - "Overview": "index.md"
  - "User guide":
      - "Tutorial": "tutorial.md"
      # - TODO: How to guide, deploying a simple app.
      # - TODO: How to guide, managing system users with systemd-sysusers.
  - "Reference":
      - "Directory layout": "directory_layout.md"
      - "Manifests": "manifests.md"
      - "Deployment phases": "deployment_phases.md"
  # - "Internals":
  #     - "The store": "store.md"
  # - "Development":
  #     - "Building": "building.md"
  #     - "About": "about.md"
